# Checkin tests workflow

name: Checkin tests

on: push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Graphviz
      uses: kamiazya/setup-graphviz@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r silicon/requirements.txt
    - name: Pytest
      run: |
        pwd
        cd unit_tests
        pytest
